### ISSUE TITLE
API Gateways

### ISSUE THREAD

**Issue by ostranme** [DoDCIO/eads#88]
Should API gateways be included at a high level? API gateways can be used to monitor, throttle, and control access to the API. The following can be done by a gateway or by the RESTful service.

- Monitor usage of the API (Activity usage)
- Throttle and rate limit API usage (DOS attack,  block malicious IP address, quotas, etc.)
- API key storage and management

**Comment by killerbgt** [comment]
It might be worth having a supplemental document describing API gateways and their benefits, but I think it's outside the scope of the handbook.
